### ISSUE TITLE
CEA Figure

### ISSUE THREAD

**Issue by rezayas** [HPM573/Labs_MarkovModel#1]
I am trying to create a cost-effectiveness figure (run [CompareTherapies.py](https://github.com/HPM573/Labs_MarkovModel/blob/master/CompareTherapies.py)) but labels of strategies show in not a very good place. Any suggestion on what we can change in [EconEvalClasses.py](https://github.com/HPM573/HPM573_SupportLib/blob/master/scr/EconEvalClasses.py) [and make sure to pull first]?

![image](https://user-images.githubusercontent.com/25065190/37408853-563847f0-2773-11e8-8182-0624d8b0cbc7.png)

**Comment by yanqi8** [comment]
In the show_CE_plane function, the part controls label is
`      # show names of strategies
        if show_names:
            if not show_clouds:
                for label, x, y in zip(data['Name'], data['E[Effect]'], data['E[Cost]']):
                    plt.annotate(
                        label, xy=(x, y), xycoords='data', xytext=(x - 0.6, y + 0.3),
                        textcoords='data', weight='bold')
`
**xytext=(x - 0.6, y + 0.3)** controls the location of label, which are the expected value of the strategies. Maybe we can change it to **xytext=(x - 0.6, y - 0.5)**? But I'm afraid this is really case by case.

**Comment by rezayas** [comment]
One easy solution could be to calculate 
**Lx** = Maximum effect - Minimum effect
**Ly** = Maximum cost - Minimum cost

and then instead of using xytext=(x - 0.6, y + 0.3), we would use **xytext=(x - 0.05*Lx, y + 0.05*Ly)**.

**Comment by yanqi8** [comment]
Oh that's right! I changed the code accordingly, does it looks better now?

**Comment by rezayas** [comment]
Huge improvement. I however noticed that if the labels are big, it doesn't work well. The reason is the x and y in `xytext=(x, y)` points to the left hand side of the text box (not the middle of it). I don't want you to spend too much time on it but I wonder if you know how to modify the code so that we `x - 0.05 * Lx, y + 0.04 * Ly` points to the middle of the text box (not the left corner)! 

![image](https://user-images.githubusercontent.com/25065190/37467492-beda9b32-2836-11e8-9aad-94d670f83ecd.png)

**Comment by yanqi8** [comment]
Updated. I found the argument **ha** would do the trick. In our test plot it now looks like this:
<img width="386" alt="screen shot 2018-03-15 at 10 45 01 am" src="https://user-images.githubusercontent.com/34167870/37470931-073ab922-283f-11e8-980e-0c1ad06e15dc.png">

**Comment by rezayas** [comment]
Wonderful! Looks great.

![image](https://user-images.githubusercontent.com/25065190/37471431-0d16e7a2-2840-11e8-8bf3-8b1a405adf65.png)
